# Generated by Django 4.2.7 on 2023-11-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis_De_Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('Operacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='permiso_de_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('Operacion', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
